; This file was auto-generated by drush make

core = 7.x
api = 2

; Projects
projects[drupal][version] = "7.23"

projects[apachesolr][subdir] = "contrib"
projects[apachesolr][version] = "1.5"

projects[coder][subdir] = "contrib"
projects[coder][version] = "1.2"

projects[context][subdir] = "contrib"
projects[context][version] = "3.1"

projects[context_filter][subdir] = "contrib"
projects[context_filter][version] = "1.1"

projects[context_inline_editor][subdir] = "contrib"
projects[context_inline_editor][version] = "1.x-dev"
projects[context_inline_editor][patch][0] = "http://drupal.org/files/filter_context_1327672-5.patch"

projects[ctools][subdir] = "contrib"
projects[ctools][version] = "1.3"

projects[content_access][subdir] = "contrib"
projects[content_access][version] = "1.2-beta2"

projects[date][subdir] = "contrib"
projects[date][version] = "2.6"

projects[delta][subdir] = "contrib"
projects[delta][version] = "3.0-beta11"

projects[danishstemmer][subdir] = "contrib"
projects[danishstemmer][version] = "1.1"

projects[diff][subdir] = "contrib"
projects[diff][version] = "3.2"

projects[dynamic_background][subdir] = "contrib"
projects[dynamic_background][version] = "1.11"

projects[better_formats][subdir] = "contrib"
projects[better_formats][version] = "1.0-beta1"

projects[facetapi][subdir] = "contrib"
projects[facetapi][version] = "1.3"

projects[features][subdir] = "contrib"
projects[features][version] = "2.0"

projects[file_entity][subdir] = "contrib"
projects[file_entity][version] = "2.0-alpha3"

projects[fontyourface][subdir] = "contrib"
projects[fontyourface][version] = "2.8"

projects[globalredirect][subdir] = "contrib"
projects[globalredirect][version] = "1.5"

projects[google_analytics][subdir] = "contrib"
projects[google_analytics][version] = "1.4"

projects[media][subdir] = "contrib"
projects[media][version] = "2.0-alpha3"

projects[migrate][subdir] = "contrib"
projects[migrate][version] = "2.5"

projects[migrate_extras][subdir] = "contrib"
projects[migrate_extras][version] = "2.5"

projects[menu_block][subdir] = "contrib"
projects[menu_block][version] = "2.3"

projects[module_filter][subdir] = "contrib"
projects[module_filter][version] = "1.8"

projects[mollom][subdir] = "contrib"
projects[mollom][version] = "2.8"

projects[insert][subdir] = "contrib"
projects[insert][version] = "1.3"

projects[job_scheduler][subdir] = "contrib"
projects[job_scheduler][version] = "2.0-alpha3"

projects[jquery_update][subdir] = "contrib"
projects[jquery_update][version] = "2.3"

projects[libraries][subdir] = "contrib"
projects[libraries][version] = "2.1"

projects[link][subdir] = "contrib"
projects[link][version] = "1.1"

projects[nodespotbox][subdir] = "contrib"
projects[nodespotbox][version] = "1.7"

projects[markdown][subdir] = "contrib"
projects[markdown][version] = "1.2"

projects[omega_tools][subdir] = "contrib"
projects[omega_tools][version] = "3.0-rc4"

projects[omega_ui][subdir] = "contrib"
projects[omega_ui][version] = "2.x-dev"

projects[page_title][subdir] = "contrib"
projects[page_title][version] = "2.7"

projects[pathauto][subdir] = "contrib"
projects[pathauto][version] = "1.2"

projects[persona][subdir] = "contrib"
projects[persona][version] = "1.15"

projects[panels][subdir] = "contrib"
projects[panels][version] = "3.3"

projects[redirect][subdir] = "contrib"
projects[redirect][version] = "1.0-rc1"

projects[securepages][subdir] = "contrib"
projects[securepages][version] = "1.x-dev"

projects[token][subdir] = "contrib"
projects[token][version] = "1.5"

projects[views][subdir] = "contrib"
projects[views][version] = "3.7"

projects[workbench][subdir] = "contrib"
projects[workbench][version] = "1.2"

projects[workbench_media][subdir] = "contrib"
projects[workbench_media][version] = "1.1"

projects[wysiwyg][subdir] = "contrib"
projects[wysiwyg][version] = "2.2"

projects[omega][type] = "theme"
projects[omega][version] = "3.1"

; Libraries
libraries[tinymce][download][type] = "get"
libraries[tinymce][download][url] = "https://github.com/downloads/tinymce/tinymce/tinymce_3.4.2.zip"
libraries[tinymce][directory_name] = "tinymce"
libraries[tinymce][destination] = "libraries"

